[project]
name = "raspi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shakir Gamzaev", email = "shkir100@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "opencv-python>=5.0.0.93",
]

[project.scripts]
raspi = "raspi:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
